Draft/opl gr
RoboCupAtHomeJP/AtHome2024 pull request #3
Opened 2024-02-16 00:34 UTC by MrKeith99

General Rules was updated.
This pull request is still a draft, so other participant teams can also contribute in the development of the rules.

2024-03-11 13:54 UTC, akinobu1998 requested changes
ざっと日本語版を確認しました．気になったところにコメント入れています．

2024-03-11 13:54 UTC, akinobu1998 commented on rules/OPL/gr_ja.md
> +1. **メイヤー変更 (Major changes)**: 日常の環境で完全に静止することが期待できない家具（事前に定義された場所にあるかどうかに関係なく）は，テスト間でわずかに移動する場合がある．
```suggestion
1. **メジャー変更 (Major changes)**: 日常の環境で完全に静止することが期待できない家具（事前に定義された場所にあるかどうかに関係なく）は，テスト間でわずかに移動する場合がある．
```

2024-03-11 13:54 UTC, akinobu1998 commented on rules/OPL/gr_ja.md
> +- living room
各家具に固有名詞を振りたいですね．
ゴミ箱とか道具箱とか…

2024-03-11 13:54 UTC, akinobu1998 commented on rules/OPL/gr_ja.md
> +*RCJ2024*の一部の競技では，人やオブジェクトが見つかる*Predefined Location*が関与される．
```suggestion
*RCJ2024*の一部の競技では，人やオブジェクトが見つかる*Predefined Location*が設定される．
```

2024-03-11 13:54 UTC, akinobu1998 commented on rules/OPL/gr_ja.md
> +部屋の名前，事前定義された場所，および場所のクラスは*Setup Days*に発表される．
場所の名前，いつ公開がいいでしょうか．

現状のルールブックにあbin_bなどの記述があるため，できれば事前定義してその名前を使用したいです．
世界大会では確かにsetup dayまで地図や名前は出てきませんが，一方，tidy upの元となっているWRCでは部屋の名前は既知なので，判断難しいところです．
ここで決定難しそうでしたら次のTCミーティングの議題としましょう．

2024-03-11 13:54 UTC, akinobu1998 commented on rules/OPL/gr_ja.md
> +  - VLAN（無線ネットワーク）をブロードキャストしないこと
VLANをブロードキャストしないのところ，
VLANと無線ネットワークの関係がよくわかりませんでした．

VLANは何のことを指していますか？

2024-03-11 13:54 UTC, akinobu1998 commented on rules/OPL/gr_ja.md
> +1. **Technical Challenge**: *Robot Inspection*に合格したすべてのチームは，*Technical Challenge*（旧: Finals）に参加する権利がある．
Technical ChallengeはOpen Challengeに改名されませんでしたっけ？
Tech Ch: 決められた課題を解く
Open Ch: 各チーム独自のテーマでデモ
と整理されたような記憶があります．

2024-03-12 03:55 UTC, MrKeith99 commented on rules/OPL/gr_ja.md
> +部屋の名前，事前定義された場所，および場所のクラスは*Setup Days*に発表される．
やはり世界大会の方では，Setup Dayに公開されていますが，JapanOpenでは物体（標準物体），家具，場所の名前をルールの最終版とともに公開しても大丈夫かと思います．
ただし，環境のレイアウトやゲストの名前，飲み物の名前などはSetup Dayに公開した方が良いと思います．

2024-03-12 03:57 UTC, MrKeith99 commented on rules/OPL/gr_ja.md
> +  - VLAN（無線ネットワーク）をブロードキャストしないこと
```suggestion
  - 無線ネットワークをブロードキャストしないこと
```
確かに，こちらは無線ネットワークのことだけを指しています．

2024-03-12 04:01 UTC, MrKeith99 commented on rules/OPL/gr_ja.md
> +1. **Technical Challenge**: *Robot Inspection*に合格したすべてのチームは，*Technical Challenge*（旧: Finals）に参加する権利がある．
なるほど．印象に残ったのはFinalという名前をTechnical Challengeにした覚えがありましたが，その後Open Challengeになった先までわかりませんでした．
そうしたら，`Open Challenge`に統一した方が良いと思います．
```suggestion
1. **Technical Challenge**: *Robot Inspection*に合格したすべてのチームは，*Open Challenge*（旧: Finals）に参加する権利がある．
```

2024-03-14 04:57 UTC, MrKeith99 commented on rules/OPL/gr_ja.md
> +  - chair_b
以下の命名を考えました．

```suggestion
- living_room
  - left_bin
  - right_bin
  - left_box
  - right_box
  - placing_table
    - left_tray
    - right_tray
    - container
    - pen_holder
  - grasping_table
  - tall_table
- dining_room
  - shelf
  - left_chair
  - right_chair
```

2024-03-14 04:57 UTC, MrKeith99 commented on rules/OPL/gr_en.md
> +1. **Technical Challenge**: In the *Technical Challenge*, both robots can be used simultaneously.
```suggestion
1. **Open Challenge**: In the *Open Challenge*, both robots can be used simultaneously.
```

2024-03-14 04:57 UTC, MrKeith99 commented on rules/OPL/gr_en.md
> +1. **Technical Challenge**: All qualified teams have the right to participate in *Technical Challenge* (previously known as *Final*).
```suggestion
1. **Open Challenge**: All qualified teams have the right to participate in *Open Challenge* (previously known as *Final*).
```

2024-03-14 04:57 UTC, MrKeith99 commented on rules/OPL/gr_en.md
> +1. **Technical Challenge**: The score is normalized.
```suggestion
1. **Open Challenge**: The score is normalized.
```

2024-03-14 04:57 UTC, MrKeith99 commented on rules/OPL/gr_en.md
> +> *Regular Tasks* scoring is independent from the *Technical Challenge* scoring.
```suggestion
> *Regular Tasks* scoring is independent from the *Open Challenge* scoring.
```

2024-03-14 04:57 UTC, MrKeith99 commented on rules/OPL/gr_en.md
> +1. **Technical Challenge**: During the *Technical Challenge*, the number of team members inside the *Arena* is not limited.
```suggestion
1. **Open Challenge**: During the *Open Challenge*, the number of team members inside the *Arena* is not limited.
```

2024-03-14 04:57 UTC, MrKeith99 commented on rules/OPL/gr_ja.md
> +1. **Technical Challenge**: *Technical Challenge*では，両方のロボットを同時に使用することができる．
```suggestion
1. **Open Challenge**: *Open Challenge*では，両方のロボットを同時に使用することができる．
```

2024-03-14 04:57 UTC, MrKeith99 commented on rules/OPL/gr_ja.md
> +大会は，*Robot Inspection*，競技タスク，そして*Technical Challenge*という流れで進行される．
```suggestion
大会は，*Robot Inspection*，競技タスク，そして*Open Challenge*という流れで進行される．
```

2024-03-14 04:57 UTC, MrKeith99 commented on rules/OPL/gr_ja.md
> +1. **Technical Challenge**: スコアは正規化される．
```suggestion
1. **Open Challenge**: スコアは正規化される．
```

2024-03-14 04:57 UTC, MrKeith99 commented on rules/OPL/gr_ja.md
> +> *競技タスク*のスコアリングは*Technical Challenge*のスコアリングとは独立している．
```suggestion
> *競技タスク*のスコアリングは*Open Challenge*のスコアリングとは独立している．
```

2024-03-14 04:57 UTC, MrKeith99 commented on rules/OPL/gr_ja.md
> +1. **Technical Challenge**: *Technical Challenge*中，*Arena*内のチームメンバーの数に制限はない．
```suggestion
1. **Open Challenge**: *Open Challenge*中，*Arena*内のチームメンバーの数に制限はない．
```

2024-03-19 05:19 UTC, MrKeith99 commented on rules/OPL/gr_ja.md
> +  - chair_b
GPSRタスクの関係で，`Left`か`Right`の命名を利用しないとTCミーティングで決定

2024-03-19 05:31 UTC, MrKeith99 commented on rules/OPL/gr_ja.md
> +  - chair_b
```suggestion
- living_room
  - trash_bin_a
  - trash_bin_b
  - storage_box_a
  - storage_box_b
  - long_table_a
    - tray_a
    - tray_b
    - container
    - pen_holder
  - long_table_b
  - tall_table
- dining_room
  - shelf
  - chair_a
  - chair_b
```

2024-03-19 05:58 UTC, MrKeith99 commented on rules/OPL/gr_ja.md
> +部屋の名前，事前定義された場所，および場所のクラスは*Setup Days*に発表される．
```suggestion
また，*Arena*には*Entrance*という名前の*Door*があり，*Arena*への出入り口となる．
部屋の名前，事前定義された場所，および場所のクラスは基本的にルールブックと同時に公開される．
ただし，*Door Open*により競技が開始しない場合，その*開始位置*や*終了位置*は*Setup Days*に発表される．
```

2024-03-19 05:58 UTC, MrKeith99 commented on rules/OPL/gr_en.md
> +Room names, predefined locations, and location classes are announced during the *Setup Days*.
```suggestion
Room names, predefined locations, and location classes are announced at the same time as the Rulebook.
However, if the task begins without the *Door Open*, the *Starting Location* and the *Ending Location* are announced during the *Setup Days*.
```

2024-03-19 07:24 UTC, merged