[UPD] update rules based on RCJ2023 feedback (not finished)
RoboCupAtHomeJP/AtHome2024 pull request #4
Opened 2024-02-16 00:35 UTC by MrKeith99

`Receptionist` task was updated.
This pull request is still a draft, so other participant teams can also contribute in the development of the rules.

2024-03-16 10:51 UTC, akinobu1998 requested changes

2024-03-16 10:51 UTC, akinobu1998 commented on rules/OPL/rc_ja.md
> +ボランティアは競技チームによって自由に選ばれ，以下のタスクを行う．
確認です．
Aチーム，Bチームがあったとして，
Aチームのゲスト役はBチームが行いますか？

ボランティアを確実に確保するため，set up dayにボランティアをTCへ報告するとした方がいいかもしれません．

2024-03-16 10:51 UTC, akinobu1998 commented on rules/OPL/rc_ja.md
> +- 競技前:
席替えの有無についても指示するようにしましょう．

2024-03-19 06:42 UTC, MrKeith99 commented on rules/OPL/rc_ja.md
> +ボランティアは競技チームによって自由に選ばれ，以下のタスクを行う．
ボランティア(Guest役)はチームが自由に決めます．
一方で，Aチームが競技する場合，RefereeになるメンバーはBチームから1名が必要となります．

SetupDayのアナウンスの件は承知しました．そのようにしましょう．

2024-03-19 06:54 UTC, MrKeith99 commented on rules/OPL/rc_ja.md
> +   - *living room*で人々を配置（および再配置）する．
```suggestion
   - *living room*の席に座っている1番目のゲストに席替えの有無とそのタイミングを指示する．
```

2024-03-19 06:54 UTC, MrKeith99 commented on rules/OPL/rc_ja.md
> +- 競技前:
情報漏れがないように競技中にその指示した方がいいかもしれません．

2024-03-19 06:54 UTC, MrKeith99 commented on rules/OPL/rc_ja.md
> +- 競技が始まる5分前に集まる．
```suggestion
- 競技が始まる30分前に集まる．
```

2024-03-19 06:54 UTC, MrKeith99 commented on rules/OPL/rc_en.md
> +- Gather five (5) minutes before the test starts.
```suggestion
- Gather thirty (30) minutes before the test starts.
```

2024-03-19 06:54 UTC, MrKeith99 commented on rules/OPL/rc_en.md
> +   - Arrange (and re-arrange) people in the *living room*.
```suggestion
   - Announce to the first guest who is sit in the *living room*, to *Switching Places* if required.
```

2024-03-19 07:26 UTC, merged