Draft/opl RI
RoboCupAtHomeJP/AtHome2024 pull request #7
Opened 2024-03-14 10:36 UTC by MrKeith99

2024-03-14 10:45 UTC, MrKeith99 commented on rules/OPL/ri_en.md
> +  - **Ending Location**: The robot will move towards the `Room2: Dining Room`.
```suggestion
  - **Ending Location**: The robot will move towards the *Room2: Dining Room*.
```

2024-03-14 10:45 UTC, MrKeith99 commented on rules/OPL/ri_ja.md
> +- 競技が始まる5分前に集まる．
```suggestion
- 競技が始まる**30分**前に集まる．
```

2024-03-14 10:45 UTC, MrKeith99 commented on rules/OPL/ri_en.md
> +- Gather thirty (30) minutes before the test starts.
```suggestion
- Gather **thirty (30) minutes** before the test starts.
```

2024-03-16 10:57 UTC, akinobu1998 requested changes

2024-03-16 10:57 UTC, akinobu1998 commented on rules/OPL/ri_en.md
> +   - TCが1名競技の最中に経路を妨害し，ロボットがTCを避ける／停止するか確認する．
```suggestion
```

2024-03-16 10:57 UTC, akinobu1998 commented on rules/OPL/ri_ja.md
> +競技で使用されるそれぞれの種類のロボットが*Robot Inspection*に参加する必要がある．
```suggestion
> 競技によってロボットに搭載されるセンサやアクチュエータを変更する場合，
使用されるそれぞれの種類のロボットが*Robot Inspection*に参加する必要がある．
```

2024-03-19 07:28 UTC, merged